### ISSUE TITLE
"backbutton" event no longer seems to work

### ISSUE THREAD

**Issue by AshleyScirra** [apache/cordova-android#1106]
# Bug Report

## Problem
The [backbutton](https://cordova.apache.org/docs/en/9.x/cordova/events/events.html#backbutton) event no longer seems to work.

### What is expected to happen?
Adding the "backbutton" event should cause the event handler to run when pressing the back button.

### What does actually happen?
The app quits (as if there was no back button handler at all).

## Information
I'm pretty sure this used to work, so it seems like it's a regression in the latest version of Cordova, or may be related to the latest version of Android or API target.

### Command or Code
A trivial back button test ought to demonstrate the problem.

Here's a debug APK build that demonstrates the problem in a larger example: https://www.dropbox.com/s/nuxp0nq4lqm4uyw/back%20button%20test.android.debug.apk?dl=0

Touch the orange square, then press back. It should go back to the first screen, but instead it quits the app.

### Environment, Platform, Device
Tested on a Pixel 3 running Android 11

### Version information
Tested using cordova-android@9.0.0, built via the CLI

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by C3GameDev** [comment]
Hey,
is there any plan to fix this issue?
I guess it's a problem from Android 8+, tested it with Android 10 + 11 -> error. On Android 7 it's working fine.

It's an important feature since it's required to comply with the "Android Core App Quality Guidelines"!

Thanks for the help!

**Comment by th3hamm0r** [comment]
We currently also have this issue, but in our case, the "backbutton"-event works after the user touches the app screen.

So if we register a listener for the event in "deviceready" and press the backbutton directly after the app start, on older devices (eg. Android 6), it gets fired, but on devices with Android 10 or 11 it doesn't (instead it closes the app). On those devices the user has to touch the app screen first. After that, if back is pressed, the backbutton-event fires.

We've tried it with the latest Cordova Android 9.1.0.

**Comment by NiklasMerz** [comment]
I just did a quick test on my Android 11 device and it works just fine. Make sure you are adding the even listener in "deviceready". 

Maybe another plugin is interfering with the event?

**Comment by C3GameDev** [comment]
I think it's a problem with cordova splashscreen plugin, the following fixed the issue for me:
Open app->java->org.apache.cordova->splashscreen and delete line 103 ("getView().setVisibility(View.INVISIBLE);")
After that everything works fine.

**Comment by erisu** [comment]
Can you try the main branch of the splashscreen plugin to see if it was fixed?

There was a commit that I believe that might have fixed the focus of the view.

https://github.com/apache/cordova-plugin-splashscreen/commit/66d1e00e003fb2f935cdbb8a5b0e47b416836b68

**Comment by NiklasMerz** [comment]
@erisu I just tested it with master. It's fixed there. Maybe we should consider releasing the plugin.

**Comment by NiklasMerz** [comment]
A new version of the splashscreen plugin has been release. This should be solved now.

https://cordova.apache.org/news/2022/04/06/splashscreen-plugin-release.html

**Comment by CodeWithOz** [comment]
I'm still having this problem despite using the latest version of the splashscreen plugin. What else could be going on?

**Comment by CodeWithOz** [comment]
I tried @C3GameDev 's suggestion above but that didn't work either. Any other ideas to try?

**Comment by jceciliano** [comment]
error continue last version splash screen,
any solution??

**Comment by NiklasMerz** [comment]
When I run cordova-android@11 without the splashscreen plugin it works fine.

**Comment by jceciliano** [comment]
> When I run cordova-android@11 without the splashscreen plugin it works fine.

ok i remove splash but error continue, i need to remove preferenaces config.xml?

<preference name="SplashScreen" value="screen"/>
<preference name="AutoHideSplashScreen" value="true"/>
 <preference name="FadeSplashScreen" value="true"/>
  <preference name="FadeSplashScreenDuration" value="250"/>
<preference name="ShowSplashScreenSpinner" value="false"/>
 <preference name="SplashScreenDelay" value="1000"/>

**Comment by breautek** [comment]
> > When I run cordova-android@11 without the splashscreen plugin it works fine.
> 
> ok i remove splash but error continue, i need to remove preferenaces config.xml?

This is a closed issue that was originally reported against cordova-android@9. If the backbutton event is not working on cordova-android@11 it might not be the same issue as the original poster.

If you use `cordova-plugin-googlemaps`, then read on, if not you can skip this blob of text. As posted https://github.com/apache/cordova-android/issues/1106#issuecomment-1192345495, there is a known issue where the `cordova-plugin-googlemaps` will intercept the `backbutton` event, and the plugin only supports handling one event handler. So if you're using this plugin, you must wait for the `deviceready` event to ensure plugins are initialised before attaching the `backbutton` event  handler. If you need more than 1 handler, then you will have to raise the issue with the maintainers of the `cordova-plugin-googlemaps` plugin. If plugins that intercept or override cordova APIs, it's on them to ensure they still work as expected. This isn't an issue with cordova-android.

If you do not use the google maps plugin then I'd suggest opening a new issue with the issue form filled so that we can understand the current environment in todays context. More than likely it's a conflict with a plugin (not necessarily the splashscreen plugin). Creating a [minimal reproduction app](https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md) will go a long ways in helping us understand the context and reproduction of the issue.

Kind regards,
Norman

**Comment by jceciliano** [comment]
ok i create new basic app using this code and can you check screenshots and test.apk, any solutions?  
http://octopus.com.mx/errorbackevent/

Code:
ons.ready(function() {
  console.log("Onsen UI is ready!");
  document.addEventListener("deviceready", onDeviceReady, false);
});

if (ons.platform.isIPhoneX()) {
  document.documentElement.setAttribute('onsflag-iphonex-portrait', '');
  document.documentElement.setAttribute('onsflag-iphonex-landscape', '');
}

function onDeviceReady() {
    // Now safe to use device APIs
    alert("onDeviceReady device APIs");

    document.addEventListener("resume", fOnResume, false);
    document.addEventListener ("backbutton", function (e) {
        e.preventDefault ();
        alert("onBackKeyDown");
        return false;
    }, false);
}

function fOnResume(){
    alert("fOnResume");
 
}

only using plugin splash screen
